// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYqyeDIo8xw_D0LSKKc5rYoPVr3vYx6Mc',
    appId: '1:379555223416:web:f9509a90b35742b5f01a8d',
    messagingSenderId: '379555223416',
    projectId: 'bookopedia-app',
    authDomain: 'bookopedia-app.firebaseapp.com',
    storageBucket: 'bookopedia-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEBJpbhNZFWqu58G_jx1NtOUAMON7Jykc',
    appId: '1:379555223416:android:96126d2de2b70fe0f01a8d',
    messagingSenderId: '379555223416',
    projectId: 'bookopedia-app',
    storageBucket: 'bookopedia-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLMBl8EXuPxxloNqGWQVuYCO8YSMiFxoo',
    appId: '1:379555223416:ios:aac2cb175ffd8d45f01a8d',
    messagingSenderId: '379555223416',
    projectId: 'bookopedia-app',
    storageBucket: 'bookopedia-app.appspot.com',
    iosClientId: '379555223416-lehgcv6s17u8h10a3minoak7q5hhv92a.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookopedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLMBl8EXuPxxloNqGWQVuYCO8YSMiFxoo',
    appId: '1:379555223416:ios:aac2cb175ffd8d45f01a8d',
    messagingSenderId: '379555223416',
    projectId: 'bookopedia-app',
    storageBucket: 'bookopedia-app.appspot.com',
    iosClientId: '379555223416-lehgcv6s17u8h10a3minoak7q5hhv92a.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookopedia',
  );
}
